#!/usr/bin/env python3
"""One leading recurrent-mean diagnostic, retaining exact external count law."""
import os
for key in ('OPENBLAS_NUM_THREADS', 'OMP_NUM_THREADS', 'MKL_NUM_THREADS'):
    os.environ[key] = '1'
import argparse
import shutil
import time
import numpy as np
from campaign import ROOT, read, write, sha
import dynamic_poisson_external_pilot as previous
import dynamic_individual_source_pilot as base

OUT = ROOT/'dynamic_mean_input_pilot'


class MeanInputNetwork(previous.PoissonNetwork):
    def arrivals(self):
        super().arrivals()
        self.arr[2:].fill(0.)


def prepare():
    OUT.mkdir(exist_ok=True);assert not (OUT/'contract.json').exists()
    assert read(ROOT/'dynamic_colored_memory_preparation/result.json')['representation_retained'] is False
    write(OUT/'contract.json', dict(status='REGISTERED_ONE_LEADING_MEAN_DIAGNOSTIC', created_epoch=time.time(),
        question='Can the freely generated recurrent mean retain the native high-state spatial and feedback behavior when the additional independent recurrent residual approximation is omitted?',
        motivation='Source-temporal audit shows the independent white residual exaggerates filtered variance; AR64 fails to represent the source-derived residual spectrum. A leading-mean diagnostic separates free recurrent mean dynamics from the added residual approximation before constructing a more complicated covariance model.',
        design='One1s trajectory,40000 physicaltargets x64 numericalreplicas, from samecomplete72s nativehighstate. Exact individualthresholds, original delays/weights, percellfixednu and Poisson externalcounts; Z/K held, membrane/synapse/ref/M/G evolve. Mean recurrent arrivals are generated by the models own source probabilities. Set only added recurrent fluctuationvariance tozero; no neural teacher forcing, phaseperiod, biological parameter or amplitude fitting.',
        pairing='MainGaussian and externalPoisson RNG streams identical to completed Poisson-external assay. Gaussian recurrent draws are still consumed but do not contribute. Countlaw, complete initialstate and mean operators remain identical.',
        limits='This deliberately omits finite-network recurrent residuals and their source correlations. It is a leading mean-input diagnostic, not a claim they vanish in the native system. Retaining one conditional state would permit further independent correspondence and finite-noise checks, not certify a stablebranch or entireloop.',
        stop='One1s only with the same native relevance guards; no automatic parameter, order, horizon, root or bifurcation calculation.',
        producer_sha256=sha(__file__), previous_sha256=sha(previous.__file__), base_sha256=sha(base.__file__),
        formal_bifurcation_allowed=False))
    shutil.copy2(__file__, OUT/'producer.py')


def qa(e):
    cp = e.cp;rng = np.random.default_rng(930233)
    history = rng.uniform(0, 10, size=e.source_history.shape);e.source_history[:] = cp.asarray(history)
    tick = e.depth-1;e.clock[0] = tick;e.arrivals()
    x = history[(tick-np.arange(1, e.depth)) % e.depth].ravel()
    expected = np.array([e.ops_cpu[0][0]@x, e.ops_cpu[1][0]@x])
    mean_error = float(abs(e.arr.get()[:2]-expected).max());assert mean_error < 1e-8
    assert np.array_equal(e.arr.get()[2:], np.zeros((2, e.N)))
    e.reset()
    for _ in range(100):e.step()
    keys = ['state', 'ref', 'rng', 'external_rng', 'history', 'source_history', 'clock', 'global_state', 'output', 'global_output']
    ref = {k: getattr(e, k).get() for k in keys}
    e.graph();e.chunk()
    equal = {k: np.array_equal(a, getattr(e, k).get()) for k, a in ref.items()};assert all(equal.values())
    e.reset()
    return dict(status='PASS', mean_operator_max_error=mean_error, added_recurrent_variance_exactzero=True,
        exact_external_count_kernel_reused=True, captured_bitwise=equal)


def run(device):
    c = read(OUT/'contract.json');assert c['producer_sha256'] == sha(__file__) and c['previous_sha256'] == sha(previous.__file__) and c['base_sha256'] == sha(base.__file__)
    assert not (OUT/'supervisor.json').exists();started = time.time()
    write(OUT/'supervisor.json', dict(status='RUNNING_ONE_LEADING_MEAN_DIAGNOSTIC', pid=os.getpid(), updated_epoch=time.time()))
    e = MeanInputNetwork(base.REPLICAS, device);write(OUT/'implementation_qa.json', qa(e));print('LEADING MEAN QA PASS', flush=True)
    e.graph();groups = [];globals_ = [];cells = []
    for offset in range(0, 1000, 10):
        groups.append(e.chunk().astype('f4'));globals_.append(e.global_output.get());cells.append(e.source_output.get().astype('f4'))
        if (offset+10) % 100 == 0:
            write(OUT/'progress.json', dict(status='RUNNING', pid=os.getpid(), elapsed_simulation_ms=offset+10,
                elapsed_wall_s=time.time()-started, updated_epoch=time.time()));print('LEADING MEAN', offset+10, flush=True)
    value, glob, source = np.concatenate(groups), np.concatenate(globals_), np.concatenate(cells)
    assert int(e.clock.get()[0]) == 10000 and np.isfinite(value).all() and np.isfinite(glob).all()
    assert np.array_equal(e.state.get()[:, :, 6:8], e.initial_state.get()[:, :, 6:8])
    with np.load(previous.OUT/'final_state.npz') as ref:
        assert np.array_equal(e.rng.get(), ref['rng']) and np.array_equal(e.external_rng.get(), ref['external_rng'])
    np.savez_compressed(OUT/'trajectory.npz', elapsed_time_ms=np.arange(1, 1001), group_output=value,
        global_R_Hz=glob[:, 0], global_s=glob[:, 1], cell_rate_Hz=source)
    np.savez_compressed(OUT/'final_state.npz', state=e.state.get(), ref=e.ref.get(), rng=e.rng.get(), external_rng=e.external_rng.get(),
        source_history=e.source_history.get(), history=e.history.get(), clock=e.clock.get(), global_state=e.global_state.get())
    write(OUT/'result.json', dict(status='COMPLETE_ONE_LEADING_MEAN_DIAGNOSTIC_ANALYSIS_PENDING', duration_ms=1000,
        replicas=base.REPLICAS, both_numerical_RNGs_paired_bitwise=True, held_fields_bitwise=True, elapsed_s=time.time()-started,
        formal_bifurcation_allowed=False));write(OUT/'supervisor.json', dict(status='COMPLETE', updated_epoch=time.time()))


if __name__ == '__main__':
    p = argparse.ArgumentParser();p.add_argument('command', choices=['prepare', 'run']);p.add_argument('--device', type=int, default=1);a = p.parse_args()
    if a.command == 'prepare':prepare()
    else:
        try:run(a.device)
        except Exception:
            write(OUT/'supervisor.json', dict(status='FAILED', pid=os.getpid(), updated_epoch=time.time()));raise
