"""Single shooting with segmented storage of the complete variational map.

Only the nonlinear starting state and period are independent unknowns.
Intermediate states come from one uninterrupted original flow. Segmentation
limits GPU cache storage, not the physical state or the Newton derivative.
"""
from common import np,read,write,log,OUT
from onset_state_continuation import build,regrid_state
from onset_poincare_corrector import SectionReturn
from onset_segment_flow import fixed_times,SegmentDerivative
from onset_period_return import errors,dynamical_state
from core_a_multiple_shooting import segment_partition
from core_a_periodic_hookstep import krylov
from core_a_positive_newton_coordinates import retract
from fine_rate_frozen_Z_fields import restore,capture
from pathlib import Path
import argparse,os,time,gc


def main(a):
    assert 1 <= a.max_trial_evaluations <= 8
    out=Path(a.destination).resolve();out.mkdir(parents=True,exist_ok=True)
    assert not (out/'jobs.json').exists()
    assert read(OUT/'core_a_bifurcation_type_20260924/numerical_checks/refractory_projection/result.json')['status']=='PASS'
    write(out/'contract.json',dict(source=str(Path(a.source).resolve()),source_dt_ms=a.source_dt,
        dt_ms=a.dt,segments=a.segments,seed_period_ms=a.period,target_native_path_time_ms=a.target_native_time,
        method='Full-state single shooting of Phi_T(X)-X=0 plus one fixed autonomous phase plane. All intermediate states are generated by one uninterrupted original flow. Its full derivative is a product of exact segment variational maps; only cache storage is segmented. FirstK-1 durations are anchored to integer actual steps; final duration contains the period variation.',
        difference_from_multiple_shooting='Eliminate independent intermediate unknowns by original forward integration. Newton has N+1 unknowns instead of K*N+1, but N is the entire spatial/delay/M state. No physical projection or reduced rate model is introduced. Strongly unstable cycles may be less well conditioned under single shooting; failure is a solver outcome.',
        coordinates='One fixed cell-weighted cycle-RMS row scale, computed from all initial actual nodes. Trust region bounds the complete starting-state/period update in these invertible coordinates. Physical closure gates unchanged.',
        equation='Same3479-group spatial delayed rate field, original constant external input mean, physical private variance and locked response. EveryZ held and allE M dynamic. Optional parameter change only selects native withinCoreA Z along the continuous recorded field path; outsideA unchanged.',
        cache_check_mode=a.cache_check,
        acceptance='At every iteration measure original whole-cycle closure. Require combined<1e-7, everyphysicalblock<1e-6,phase<1e-9. Original cached/uncached comparisons use the declared all-segment or first/last-segment option; the unchanged cache implementation already has multi-phase validation. In either mode full original nonlinear bordered FD is required before correction. Actual nonlinear decrease and prediction agreement gate every update. Independent whole-flow, fundamental-period, phase/mesh, Floquet and critical crossing remain separate.',
        maximum_iterations=a.iterations,maximum_Krylov=a.krylov,
        maximum_trial_evaluations_per_iteration=a.max_trial_evaluations,model_promoted=False))
    jobs=dict(status='RUNNING',pid=os.getpid());write(out/'jobs.json',jobs);start=time.time()
    try:
        e=build(a.device,a.dt);base=regrid_state(dict(np.load(a.source)),e,a.source_dt)
        if a.target_native_time is not None:
            from core_a_parameter_path_audit import NativeTimeFamily
            family=NativeTimeFamily(e.s);Z,_=family.field_at_time(a.target_native_time)
            assert np.array_equal(base['syn'][5,~family.A],Z[~family.A]);base['syn'][5]=Z.copy()
        A=SectionReturn(base,e,a.period);T=float(a.period);K=a.segments
        h=round(T/K/e.dt)*e.dt;N=A.c.size;wT=.01;w=e.s.sizes/e.s.sizes.sum()
        assert T-(K-1)*h>2*e.dt
        log('WHOLE CYCLE SEED PREFIX',T,K,e.dt)
        initial=fixed_times(A,A.xref,[j*h for j in range(1,K)])
        seed_states=[base]+[A.state(y) for y,_ in initial]
        power=sum(((A.c.raw(q)**2)*(A.c.weight**2)).sum(1) for q in seed_states)/K
        A.c.scale=np.maximum(np.sqrt(power)[:,None],A.c.floor);A.xref=A.c.pack(base)
        restore(e,base);points=[A.xref]
        for _ in range(2):
            e.step();e.cp.cuda.get_current_stream().synchronize();points.append(A.c.pack(capture(e)))
        normal=(-3*points[0]+4*points[1]-points[2])/(2*e.dt);A.normal=normal/np.linalg.norm(normal)
        x=A.xref.copy();radius=a.radius*np.linalg.norm(x);rows=[]
        status='ITERATION_LIMIT_NOT_A_PERIODIC_ROOT'
        def evaluate(xx,period):
            durations,_=segment_partition(period,K,h)
            values=fixed_times(A,xx,np.cumsum(durations))
            states=[A.state(xx)]+[A.state(y) for y,_ in values[:-1]]
            for state in states:
                assert A.admissible(A.c.pack(state)),'Actual intermediate state inadmissible'
                assert np.array_equal(state['syn'][5],base['syn'][5])
            y,slope=values[-1];phase=float(A.normal@(xx-A.xref))
            check=errors(dynamical_state(A.state(xx)),dynamical_state(A.state(y)),w)
            return np.r_[y-xx,-phase],slope,check,phase,states
        for iteration in range(a.iterations):
            folder=out/f'iteration{iteration:02d}';folder.mkdir(exist_ok=True)
            log('WHOLE CYCLE EVALUATE',iteration,T)
            f,slope,check,phase,states=evaluate(x,T);norm=float(np.linalg.norm(f))
            durations,_=segment_partition(T,K,h)
            row=dict(iteration=iteration,period_ms=T,durations_ms=durations.tolist(),phase=phase,
                whole_cycle=check,max_combined_relative_rms=check['combined_relative_rms'],
                coordinate_residual=norm/np.linalg.norm(x))
            rows.append(row);write(out/'iterations.json',rows)
            for j,state in enumerate(states):np.savez_compressed(folder/f'node{j:02d}.npz',**state)
            jobs.update(iteration=iteration,stage='WHOLE_CYCLE_MATCHING',last_residual=check['combined_relative_rms']);write(out/'jobs.json',jobs)
            log('WHOLE CYCLE MATCHING',iteration,T,check['combined_relative_rms'])
            if check['combined_relative_rms']<1e-7 and max(v['relative_rms'] for v in check['blocks'].values())<1e-6 and abs(phase)<1e-9:
                status='NUMERICAL_SEGMENTED_SINGLE_SHOOTING_ROOT';break
            if iteration:
                del derivative,J,shared,parts,propose
                gc.collect();e.cp.get_default_memory_pool().free_all_blocks()
            parts=[]
            for state,t in zip(states,durations):
                B=SectionReturn(state,e,t);B.c.scale=A.c.scale.copy();B.xref=B.c.pack(state);parts.append(B)
            derivative=[None]*K;shared=None
            for j in np.argsort(-durations):
                B=parts[j];log('WHOLE CYCLE CACHE BEGIN',iteration,j)
                J=SegmentDerivative(B,B.xref,durations[j],shared=shared)
                shared=J.shared;derivative[j]=J
                if iteration==0 and (a.cache_check=='all' or j in [0,K-1]):
                    rng=np.random.default_rng(925410+int(j));v=B.xref*rng.normal(size=N);v/=np.linalg.norm(v)
                    actual=J(v);old=SegmentDerivative(B,B.xref,durations[j],cached=False);expected=old(v)
                    err=float(np.linalg.norm(actual-expected)/np.linalg.norm(expected))
                    write(folder/f'segment{j}_cache_check.json',dict(status='PASS' if err<1e-10 else 'FAIL',relative_error=err))
                    assert err<1e-10,('Segment derivative mismatch',j,err)
                    del old
                log('WHOLE CYCLE CACHE',iteration,j)
            def linear(v):
                q=v[:-1].copy()
                for J in derivative:q=J(q)
                return np.r_[v[:-1]-q-slope*(v[-1]/wT),A.normal@v[:-1]]
            if iteration==0:
                rng=np.random.default_rng(925420);v=x*rng.normal(size=N);v*=norm/np.linalg.norm(v)
                direction=np.r_[v,wT*.01];actual=linear(direction);fd=[];err=np.inf
                for epsilon in [1e-4,1e-5,1e-6]:
                    xx=x+epsilon*v
                    if not A.admissible(xx):continue
                    ff,_,_,_,_=evaluate(xx,T+epsilon*.01)
                    err=float(np.linalg.norm((ff-f)/epsilon+actual)/np.linalg.norm(actual))
                    fd.append(dict(epsilon=epsilon,relative_error=err));write(out/'bordered_derivative_check.json',fd)
                    if err<1e-3:break
                assert err<1e-3,('Whole-cycle derivative FD failed',fd)
            factor=1./(-np.expm1(-T/float(e.transport.consts[6].get())))
            def right(v):
                u=v.copy();u[:-1].reshape(-1,e.s.P)[4]*=factor;return u
            jobs.update(stage='KRYLOV');write(out/'jobs.json',jobs)
            propose,progress=krylov(lambda v:v-linear(v),f,a.krylov,folder,e.s.P,factor,
                right_override=right,operator_description='Complete [I-DPhi_T,-flow_slope;phase] shooting Newton operator, not Floquet',
                linear_tolerance=min(.01,max(1e-6,.1*np.sqrt(check['combined_relative_rms']))))
            trials=[];accepted=False
            for attempt in range(a.max_trial_evaluations+5):
                delta,small=propose(radius);tt=T+delta[-1]/wT;diagnostics={}
                xx=retract(A,x,delta[:-1],1.,project_zero=True,project_all=True,restore_phase=True,
                    diagnostics=diagnostics,orthogonal_phase=True,refractory_projection=True)
                if xx is None or not .8*a.period<tt<1.2*a.period or tt-(K-1)*h<2*e.dt:
                    trials.append(dict(status='INADMISSIBLE_NUMERICAL_PROPOSAL',diagnostics=diagnostics,**small));write(folder/'trials.json',trials);radius*=.5;continue
                effective=np.r_[xx-x,wT*(tt-T)]
                if np.linalg.norm(effective)>1.05*radius:
                    trials.append(dict(status='PROJECTION_EXCEEDS_RADIUS',diagnostics=diagnostics,**small));write(folder/'trials.json',trials);radius*=.5;continue
                if sum(t['status']=='EVALUATED' for t in trials)>=a.max_trial_evaluations:break
                ff,_,cc,pp,ss=evaluate(xx,tt);prediction=f-linear(effective)
                gain=1-float(ff@ff)/(norm*norm);predicted_gain=1-float(prediction@prediction)/(norm*norm)
                agreement=gain/predicted_gain if predicted_gain>0 else -np.inf
                trial=dict(status='EVALUATED',period_ms=tt,max_combined_relative_rms=cc['combined_relative_rms'],
                    residual_ratio=float(np.linalg.norm(ff)/norm),predicted_gain=predicted_gain,agreement=agreement,
                    diagnostics=diagnostics,**small)
                trials.append(trial);write(folder/'trials.json',trials);log('WHOLE CYCLE TRIAL',trial)
                if gain>0 and agreement>.1:
                    x=xx;T=float(tt);accepted=True
                    for j,state in enumerate(ss):np.savez_compressed(folder/f'accepted_node{j:02d}.npz',**state)
                    write(folder/'accepted_period.json',dict(period_ms=T,durations_ms=segment_partition(T,K,h)[0].tolist(),fixed_grid_segment_ms=h))
                    if agreement>.75:radius=min(2*radius,.2*np.linalg.norm(x))
                    break
                radius*=.5
            row.update(trials=trials,linear_last=progress[-1]);write(out/'iterations.json',rows)
            if not accepted:status='NO_ACCEPTED_SHOOTING_STEP_NOT_A_BIFURCATION';break
        write(out/'result.json',dict(status=status,iterations=rows,seconds=time.time()-start,
            physical_Floquet='NOT_ESTABLISHED',model_promoted=False))
        jobs.update(status='COMPLETE',scientific_status=status);write(out/'jobs.json',jobs)
    except BaseException as exc:
        jobs.update(status='FAILED',error=repr(exc));write(out/'jobs.json',jobs);raise


if __name__=='__main__':
    p=argparse.ArgumentParser();p.add_argument('source');p.add_argument('--destination',required=True)
    p.add_argument('--period',type=float,required=True);p.add_argument('--target-native-time',type=float)
    p.add_argument('--device',type=int,default=1);p.add_argument('--dt',type=float,default=.05)
    p.add_argument('--source-dt',type=float,default=.05);p.add_argument('--segments',type=int,default=6)
    p.add_argument('--iterations',type=int,default=4);p.add_argument('--krylov',type=int,default=24)
    p.add_argument('--radius',type=float,default=.005)
    p.add_argument('--max-trial-evaluations',type=int,default=4)
    p.add_argument('--cache-check',choices=['all','ends'],default='all');main(p.parse_args())
