import sys
sys.path.insert(0,'scripts/topic4_zm_runaway_mechanism')
from common import OUT,np,read,write,log
from onset_state_continuation import build
from onset_poincare_corrector import SectionReturn
from onset_cubic_section import CubicSectionReturn,CubicSectionDerivative,polynomial_check
from onset_period_return import dynamical_state,errors
import os
p=OUT/'core_a_bifurcation_type_20260924/relaxed_return_corrector/mid1_active_coarse'
out=p/'cubic_dense_check';out.mkdir(exist_ok=True);assert not(out/'jobs.json').exists()
write(out/'jobs.json',dict(status='RUNNING',pid=os.getpid()))
polynomial_check();e=build(0);base=dict(np.load(p/'root_state.npz'));T=read(p/'result.json')['rows'][-1]['period_ms']
A=CubicSectionReturn(base,e,T,5);x=A.xref;y,meta=A(x);f=y-x
err=errors(dynamical_state(A.state(x)),dynamical_state(A.state(y)),e.s.sizes/e.s.sizes.sum())
write(out/'initial.json',dict(**meta,**err));log('CUBIC ROOT RETURN',meta,err['combined_relative_rms'])
J=CubicSectionDerivative(A,x,meta['period_ms'],A.last_time_slope)
# Use a physical tangent generated by an actual short return residual, not
# arbitrary negative perturbations of near-empty local M/history components.
d=J(f);rows=[]
for eps in [.01,.003,.001]:
    assert A.admissible(x+eps*f)
    q,info=A(x+eps*f);fd=(q-y)/eps
    row=dict(epsilon=eps,relative_error=float(np.linalg.norm(fd-d)/np.linalg.norm(d)),period_ms=info['period_ms']);rows.append(row);log('CUBIC DERIVATIVE',row)
    write(out/'progress.json',rows)
write(out/'result.json',dict(status='PASS' if rows[-1]['relative_error']<1e-3 else 'FAIL',rows=rows,polynomial_check=True,initial=err,physical_model_changed=False))
write(out/'jobs.json',dict(status='COMPLETE',pid=os.getpid()))
