#!/bin/bash
# The whole v0.2 chain, in dependency order, detached.
#
# The recovery gate does NOT block the cohort. It decides which parameter-level
# statements the closeout may make; the prediction ladder never needs to know a
# true parameter value, so it runs either way. Treating a gate verdict as a stop
# sign would throw away the question the version was built to answer.
# DO NOT EDIT THIS FILE WHILE IT IS RUNNING. bash seeks back to a byte offset
# between commands, so inserting lines anywhere -- including well below the
# current point -- shifts every offset after them and the shell resumes at a
# position that no longer starts a command. On 2026-08-07 that silently skipped
# three analysis stages on the final pass, and every acceptance check still
# passed because none of them looked at whether the outputs were current.
set -u
W=/home/honglab/leijiaxin/HFOsp/.worktrees/topic5-spo-rnn
PY=/home/honglab/leijiaxin/anaconda3/envs/cuda_env/bin/python
R=$W/results/topic5_spatial_propagation_operator_v0_2
cd "$W" || exit 1
export OMP_NUM_THREADS=2 MKL_NUM_THREADS=2 PYTHONPATH="$W"
stamp() { echo "[$(date +%H:%M:%S)] $*"; }

count_done() {
  find "$R/per_subject" -path '*/seed1/*' -name DONE.json 2>/dev/null | wc -l
}
count_running() { pgrep -fc "train_topic5_spo_unit\.py"; }

# --- wait for the recovery gate, which is already running ------------------
stamp "waiting for the recovery gate"
while pgrep -f "run_topic5_spo_recovery\.py" > /dev/null; do sleep 60; done
if [ -f "$R/synthetic/RECOVERY_GATE.json" ]; then
  stamp "gate finished: $($PY -c "
import json;g=json.load(open('$R/synthetic/RECOVERY_GATE.json'))
print(' '.join(f\"{k.split('_')[0]}={g[k]['status']}\" for k in
 ('drift_sign','anisotropy_ordering','recovery_strength_ordering')))")"
else
  stamp "gate produced no verdict file; the cohort still runs, the closeout will say so"
fi

# --- first seed, five variants, every patient -----------------------------
stamp "cohort, first seed"
$PY scripts/launch_topic5_spo_cohort.py --seeds 1 --workers 6 \
  >> "$R/cohort_seed1.log" 2>&1

attempt=0
while [ "$(count_done)" -lt 105 ] && [ "$attempt" -lt 6 ]; do
  attempt=$((attempt + 1))
  stamp "retry $attempt at $(count_done)/105"
  find "$R/per_subject" -name FAILED.json -delete 2>/dev/null
  $PY scripts/launch_topic5_spo_cohort.py --seeds 1 --workers 16 \
    >> "$R/cohort_retry.log" 2>&1
done
stamp "cohort at $(count_done)/105"

# --- second seed, full operator only, for the reliability question ---------
stamp "second seed, full operator"
$PY scripts/launch_topic5_spo_cohort.py --variants ANISOTROPIC_RECOVERY \
  --seeds 2 --workers 16 >> "$R/cohort_seed2.log" 2>&1 || true

# --- leave-contact-out, strong condition only ------------------------------
# One condition, named in advance. v0.1 ran two with neither primary and spent
# its multiplicity budget on a question it only needed to ask once.
#
# Three arms, because the absolute held-out score needs a floor to be readable.
# With the withheld contact's bias neutralised, STATIC knows literally nothing
# about it -- every withheld contact gets the same number. FIELD_NULL adds a
# field that decays where contacts fired, so a withheld contact benefits only
# from the read kernel's blur. The full operator additionally transports. An arm
# that beats STATIC is using where the contact sits, and nothing else can
# explain it.
stamp "leave-contact-out, strong condition"
$PY scripts/launch_topic5_spo_cohort.py \
  --variants ANISOTROPIC_RECOVERY FIELD_NULL STATIC --seeds 1 --workers 16 \
  --holdout-fraction 0.25 --out-root "$R/leave_contact_out" \
  >> "$R/loco.log" 2>&1 || true

# --- analysis, figure, closeout, gate --------------------------------------
stamp "aggregating"
$PY scripts/analyse_topic5_spo_cohort.py >> "$R/analysis.log" 2>&1
stamp "against v0.1"
$PY scripts/compare_topic5_spo_against_v0_1.py >> "$R/analysis.log" 2>&1 || true
stamp "kernel width sweep"
$PY scripts/sweep_topic5_spo_kernel_width.py >> "$R/analysis.log" 2>&1 || true
stamp "spatial scale"
$PY scripts/check_topic5_spo_spatial_scale.py >> "$R/analysis.log" 2>&1
stamp "figure"
$PY scripts/plot_topic5_spo_figures.py >> "$R/analysis.log" 2>&1
stamp "closeout"
$PY scripts/write_topic5_spo_closeout.py >> "$R/analysis.log" 2>&1
$PY scripts/accept_topic5_spo_v0_2.py > "$R/ACCEPTANCE.txt" 2>&1
stamp "DRIVER COMPLETE"
cat "$R/ACCEPTANCE.txt"
