#!/usr/bin/env python3
"""Does the data hold directional structure the isotropic model does not?

The order-shuffle null answers a weaker question than it looks like it does.
Shuffling rank order destroys spatial contiguity as well as direction, so real
events beating it only shows that events are *local walks* -- which an isotropic
local diffusion already reproduces.

The comparison that separates the two is against the fitted models' own
generated events: take the same statistic on real held-out events, on events
generated by the isotropic model, and on events generated by each later layer.
If the real value sits inside the isotropic model's own spread, there is no
directional structure left for a direction motif to explain.  If it sits
outside, the null result of the motif ladder is a limit of the model family
rather than of the data.
"""
from __future__ import annotations

import argparse
import json
import sys
import time
from pathlib import Path

import numpy as np
import pandas as pd
import torch

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from scripts.evaluate_topic5_dynamical_motif_unseen_v0_1 import load_unit_model  # noqa: E402
from scripts.run_topic5_dynamical_motif_axial_drift_v0_1 import (  # noqa: E402
    persistence, step_vectors,
)
from src.topic5_dynamical_motif_data_v0_1 import load_frame_unit  # noqa: E402
from src.topic5_dynamical_motif_analysis_v0_1 import sequences_to_ranks  # noqa: E402
from src.topic5_dynamical_motif_rnn_v0_1 import build_motif_event_tensors  # noqa: E402
from src.topic5_dynamical_motif_rollout_v0_1 import stochastic_rollout  # noqa: E402

MODELS = ("DM0_ISOTROPIC", "DM1_FREE_AXIS", "DM2_LOCAL_DIRECTIONAL",
          "DM3_AXIS_FEEDFORWARD_TRANSIENT")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--frame", default="GEOMETRY_ONLY_PCA2")
    parser.add_argument("--tag", default="formal")
    parser.add_argument("--seed-index", type=int, default=0)
    parser.add_argument("--out-root", type=Path,
                        default=ROOT / "results/topic5_dynamical_motif_rnn_v0_1")
    parser.add_argument("--device", default="cuda:0")
    parser.add_argument("--draws", type=int, default=8)
    parser.add_argument("--max-events", type=int, default=4000)
    parser.add_argument("--gate-rule", default="M2-2RANK")
    parser.add_argument("--subjects", nargs="*", default=None)
    args = parser.parse_args()

    started = time.time()
    device = torch.device(args.device if torch.cuda.is_available() else "cpu")
    base = args.out_root / args.tag / args.frame
    subjects = args.subjects or sorted(p.name for p in base.iterdir() if p.is_dir())
    rows = []
    for subject in subjects:
        available = [m for m in MODELS
                     if (base / subject / m / f"seed{args.seed_index}" / "checkpoint.pt").exists()]
        if not available:
            continue
        unit = load_frame_unit(args.out_root, args.frame, subject)
        tensors = build_motif_event_tensors(unit.ranks, unit.contacts_xy_mm,
                                            gate_rule=args.gate_rule)
        unseen = unit.indices(-1)
        if unseen.size > args.max_events:
            unseen = unseen[np.linspace(0, unseen.size - 1, args.max_events).astype(int)]
        observed = persistence(step_vectors(unit.ranks[unseen], unit.contacts_xy_mm))
        if observed.get("n_pairs", 0) == 0:
            continue
        record = {"frame": args.frame, "subject": subject,
                  "n_contacts": unit.n_contacts,
                  "geometry_class": unit.provenance.get("geometry_class"),
                  "n_model_unseen_used": int(unseen.size),
                  "observed_cosine": observed["mean_consecutive_cosine"],
                  "observed_pairs": observed["n_pairs"]}
        starts = tensors["x"][:, 0][torch.as_tensor(unseen)]
        for model_id in available:
            unit_dir = base / subject / model_id / f"seed{args.seed_index}"
            model, head, contract, _ = load_unit_model(unit, unit_dir, device)
            per_draw = []
            for draw in range(int(args.draws)):
                result = stochastic_rollout(
                    model, head, contract, starts, unit.contacts_xy_mm, device,
                    mode="FULL_STOP", gate_rule=args.gate_rule,
                    rng_label=f"{subject}|persistence|{model_id}|{draw}")
                ranks = sequences_to_ranks(result["sequence"], result["n_emitted"])
                value = persistence(step_vectors(ranks, unit.contacts_xy_mm))
                if value.get("n_pairs", 0):
                    per_draw.append(value["mean_consecutive_cosine"])
            if not per_draw:
                continue
            per_draw = np.asarray(per_draw)
            record[f"{model_id}_cosine_mean"] = float(per_draw.mean())
            record[f"{model_id}_cosine_sd"] = float(per_draw.std(ddof=1)) if per_draw.size > 1 else float("nan")
            record[f"{model_id}_gap"] = float(observed["mean_consecutive_cosine"] - per_draw.mean())
        rows.append(record)
        gap = record.get("DM0_ISOTROPIC_gap")
        print(f"[gap] {subject}: observed={record['observed_cosine']:+.4f} "
              f"isotropic={record.get('DM0_ISOTROPIC_cosine_mean', float('nan')):+.4f} "
              f"gap={gap if gap is None else round(gap, 4)}", flush=True)

    table = pd.DataFrame(rows)
    table.to_csv(args.out_root / "PERSISTENCE_MODEL_GAP_PER_PATIENT.csv", index=False)
    summary = {"contract": "topic5_dynamical_motif_persistence_gap_v0_1",
               "frame": args.frame, "tag": args.tag, "seed_index": args.seed_index,
               "draws_per_model": int(args.draws),
               "n_subjects": int(len(table)),
               "statistic": "mean cosine between consecutive rank-set step vectors",
               "seconds": time.time() - started}
    for model_id in MODELS:
        column = f"{model_id}_gap"
        if column in table and table[column].notna().any():
            values = table[column].dropna()
            summary[model_id] = {
                "n": int(values.size),
                "median_gap": float(values.median()),
                "n_positive": int((values > 0).sum()),
                "median_model_cosine": float(table[f"{model_id}_cosine_mean"].median()),
            }
    (args.out_root / "PERSISTENCE_MODEL_GAP_SUMMARY.json").write_text(
        json.dumps(summary, indent=2, ensure_ascii=False) + "\n")
    print(json.dumps(summary, indent=1))


if __name__ == "__main__":
    main()
