"""SNN spontaneous-event scan — does a HOMOGENEOUS spiking sheet, driven by SLOW
SPATIALLY-CORRELATED noise, produce robust discrete self-terminating population
events anywhere on the (drive x noise) plane, or only the rate-field's
silent<->sustained topology with NO robust discrete band?

Faithful mirror of the rate-field (drive x sigma) joint NULL
(docs/.../step1_noise_contract §11). Three faithfulness requirements (advisor 2026-06-05):

 1. NOISE = slow (tau~150 ms) AND spatially correlated (ell~l_EE) OU field added to
    the E external rate, generated by the SAME src.sef_hfo_events.make_ou_noise used on
    the rate field. The stock engine OU (model.py / kick_probe.py) is a SCALAR/global
    field -> can only brighten the whole sheet together -> cannot nucleate a LOCAL
    event -> a NULL there would be "global noise can't seed local events", NOT
    "homogeneous tissue can't support discrete events". So we add the spatial field.

 2. OBSERVABLE = COHERENCE active fraction: per time bin, local E-active fraction per
    grid cell, spatially smoothed (ell~l_EE), then fraction of cells above a fixed
    structural crossing. A blind distinct-neuron SUM is contiguity-blind (100 scattered
    == 100 contiguous) and inflates with speckle.

 3. DETECTOR = REUSE src.sef_hfo_events.classify_run / calibrate_detector / accepted_cell
    UNCHANGED (same discreteness contract: all-returned; frac_time_on>=0.30 -> sustained;
    per-op amplitude bar = max(sigma=0, sigma_ref) floor <-> sigma=0 kick peak midpoint;
    accept rate in [0.01,1]/s). floor uses BOTH sigma=0 and a sub-threshold sigma_ref run.

Verdict is TOPOLOGICAL: a robust 2-D discrete region ANYWHERE in (drive x sigma_n) ->
"SNN shows a spontaneous discrete band" (would DIFFER from the rate-field NULL); only a
seam / single cell / silent<->sustained -> "consistent with the rate-field NULL".
sigma_n (1/ms on the Poisson rate) is INCOMMENSURABLE with the rate-field sigma (mV on
muE) -- never read the verdict "at the rate field's sigma".

Run:  PYTHONPATH=<engine>:<repo> python noise_spontaneous_scan.py --mode controls
"""
from __future__ import annotations
import argparse, json, os, sys, time
import numpy as np

REPO = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
# the spiking engine (coworker's scaffold) currently lives UNTRACKED under results/;
# import it from there until it is moved into a tracked location (flagged for the user).
ENGINE = os.path.join(REPO, "results", "topic4_sef_hfo", "lif_snn", "engine")
for pth in (ENGINE, REPO):
    if pth not in sys.path:
        sys.path.insert(0, pth)

from params import Params, compute_nu_theta
from model import build_network
from src.sef_hfo_events import (
    make_ou_noise, classify_run, calibrate_detector, accepted_cell,
    UndetectableOperatingPoint,
)
from src.sef_hfo_field import isotropic_gaussian, convolve_periodic

DATA = os.path.join(REPO, "results", "topic4_sef_hfo", "lif_snn", "data")

# ---- fixed structural constants (NOT tuned to yield events) ----
GRID_N = 24            # noise / coherence grid over the LxL sheet
ELL_NOISE = 0.40       # mm  spatial correlation length of the slow noise (~ l_EE)
TAU_NOISE = 150.0      # ms  slow afferent component (matches stock engine tau_n)
ELL_COH = 0.38         # mm  coherence smoothing length (= l_EE)
COH_CROSS = 0.04       # local E-active fraction above which a cell is "coherently active"
BIN_MS = 2.0           # ms  coherence active-fraction sampling bin
# kick reference (same geometry as kick_probe.py)
R_KICK = 0.15          # mm
T_KICK = 150.0         # ms
DUR_KICK = 18.0        # ms


def _cell_index(pos, L, n):
    c = np.clip((pos / L * n).astype(int), 0, n - 1)
    return c[:, 0], c[:, 1]            # rows, cols


def simulate_field(p, net, sigma_noise, do_kick, noise_seed=0, tau_noise=TAU_NOISE,
                   verbose=False):
    """model.simulate's loop, with (a) a slow spatially-correlated OU field added to
    the E external rate (replacing the scalar global OU), (b) optional localized kick,
    and (c) a recorded COHERENCE active-fraction series ext_coh (per BIN_MS bin).

    Returns dict(ext_coh, dt_bin_ms, rate_E_hz, wall_s).
    """
    rng = net["rng"]
    NE, NI = net["NE"], net["NI"]
    N = NE + NI
    labels = net["labels"]; pos = net["pos"]
    ampa = net["ampa_by_delay"]; gaba = net["gaba_by_delay"]
    M = net["max_delay_steps"] + 1
    dt = p.dt
    nsteps = int(round(p.T / dt))

    decay_sE = np.exp(-dt / p.tau_r_AMPA); decay_IE = np.exp(-dt / p.tau_d_AMPA)
    decay_sI = np.exp(-dt / p.tau_r_GABA); decay_II = np.exp(-dt / p.tau_d_GABA)
    tau_m = np.where(labels == 0, p.tau_m_E, p.tau_m_I).astype(np.float64)
    decay_V = np.exp(-dt / tau_m)
    ref_steps = np.where(labels == 0, int(round(p.tau_ref_E / dt)),
                         int(round(p.tau_ref_I / dt))).astype(np.int32)
    ext_incr = (tau_m / p.tau_r_AMPA) * np.where(labels == 0, p.J_ext_E, p.J_ext_I)
    ampa_bins = [d for d in range(M) if ampa[d].nnz > 0]
    gaba_bins = [d for d in range(M) if gaba[d].nnz > 0]

    nu_theta, _, _ = compute_nu_theta(p)
    nu_sig = p.nu_ext_ratio * nu_theta

    # ---- slow spatially-correlated OU noise field (E external rate) ----
    is_E = labels == 0
    rows, cols = _cell_index(pos, p.L, GRID_N)
    stim_fn = make_ou_noise(GRID_N, p.L, dt, sigma_noise, tau_noise=tau_noise,
                            ell_noise=ELL_NOISE, seed=noise_seed)

    # ---- coherence observable: precompute per-cell E counts + smoothing kernel ----
    erow, ecol = rows[is_E], cols[is_E]
    flat_E = erow * GRID_N + ecol
    En_per_cell = np.bincount(flat_E, minlength=GRID_N * GRID_N).reshape(GRID_N, GRID_N)
    En_safe = np.maximum(En_per_cell, 1)
    K_coh = isotropic_gaussian(GRID_N, p.L, ELL_COH)

    # ---- kick mask ----
    center = np.array([p.L / 2, p.L / 2])
    dist_c = np.linalg.norm(pos - center, axis=1)
    kick_mask = is_E & (dist_c <= R_KICK)
    kick_boost = 2.0 * nu_theta

    # ---- state ----
    V = np.full(N, p.V_reset); ref = np.zeros(N, dtype=np.int32)
    s_E = np.zeros(N); I_E = np.zeros(N); s_I = np.zeros(N); I_I = np.zeros(N)
    ring_sE = np.zeros((M, N)); ring_sI = np.zeros((M, N))

    bin_steps = int(round(BIN_MS / dt))
    n_bins = nsteps // bin_steps
    ext_coh = np.zeros(n_bins)
    rate_E = np.zeros(nsteps)
    bin_active = np.zeros(NE, dtype=bool)      # OR of E spikes within the current bin

    t0 = time.time()
    for t in range(nsteps):
        tm = t * dt
        field = stim_fn(tm)                     # (GRID_N, GRID_N) slow spatial OU, or 0.0 if sigma=0
        nu_vec = np.full(N, max(nu_sig, 0.0))
        if np.ndim(field):
            nu_vec[is_E] += field[erow, ecol]   # E external rate += local slow noise
        if do_kick and (T_KICK <= tm < T_KICK + DUR_KICK):
            nu_vec[kick_mask] += kick_boost
        np.maximum(nu_vec, 0.0, out=nu_vec)

        s_E *= decay_sE; s_I *= decay_sI
        slot = t % M
        s_E += ring_sE[slot]; ring_sE[slot] = 0.0
        s_I += ring_sI[slot]; ring_sI[slot] = 0.0
        ext = rng.poisson(nu_vec * dt, size=N).astype(np.float64)
        s_E += ext * ext_incr
        I_E = s_E + (I_E - s_E) * decay_IE
        I_I = s_I + (I_I - s_I) * decay_II
        I_net = I_E - I_I

        ref -= 1; np.maximum(ref, 0, out=ref)
        free = ref == 0
        Vtmp = I_net + (V - I_net) * decay_V
        V = np.where(free, Vtmp, p.V_reset)
        spk = free & (V >= p.V_th)
        V[spk] = p.V_reset; ref[spk] = ref_steps[spk]

        rate_E[t] = spk[:NE].sum()
        bin_active |= spk[:NE]
        if spk.any():
            spE = np.where(spk[:NE])[0]; spI = np.where(spk[NE:])[0]
            if spE.size:
                for d in ampa_bins:
                    ring_sE[(t + d) % M] += np.asarray(ampa[d][:, spE].sum(axis=1)).ravel()
            if spI.size:
                for d in gaba_bins:
                    ring_sI[(t + d) % M] += np.asarray(gaba[d][:, spI].sum(axis=1)).ravel()

        # flush coherence bin
        if (t + 1) % bin_steps == 0:
            b = (t + 1) // bin_steps - 1
            if b < n_bins:
                act = np.bincount(flat_E[bin_active], minlength=GRID_N * GRID_N
                                  ).reshape(GRID_N, GRID_N)
                local_frac = act / En_safe
                sm = convolve_periodic(local_frac, K_coh)
                ext_coh[b] = float((sm > COH_CROSS).mean())
                bin_active[:] = False

        if verbose and (t % max(1, nsteps // 5) == 0):
            print(f"    sim {t}/{nsteps} ({tm:.0f}ms) rE={rate_E[t]/NE/dt*1e3:.1f}Hz "
                  f"coh={ext_coh[max(0,(t//bin_steps)-1)]:.3f} "
                  f"elapsed {time.time()-t0:.0f}s", flush=True)

    return dict(ext_coh=ext_coh, dt_bin_ms=BIN_MS, rate_E_hz=rate_E / NE / dt * 1e3,
                wall_s=time.time() - t0)


def fresh(p, net, seed):
    net["rng"] = np.random.default_rng(seed)
    return net


# ---------------------------------------------------------------------------
# Controls (advisor 2026-06-05): run BEFORE the grid.
# ---------------------------------------------------------------------------
def run_controls(L, density, T, drive=0.6):
    """Noise LADDER at one drive: sigma=0 (extinction + floor), sigma=0+kick (event
    peak), then a ladder of no-kick noise fractions. One shot shows: ignition onset,
    whether the coherence observable saturates, and discrete-vs-sustained across the
    noise axis. Also tells us the right floor (sub-threshold speckle level)."""
    base = dict(g=3.6, L=L, density=density, T=T, seed=1)
    p = Params(nu_ext_ratio=drive, **base)
    nu_theta = compute_nu_theta(p)[0]
    nu_sig = drive * nu_theta
    fracs = [0.02, 0.05, 0.10, 0.20, 0.40]      # noise std as fraction of nu_sig
    print(f"[controls] L={L} density={density} T={T} drive={drive}  "
          f"nu_sig={nu_sig*1e3:.0f}Hz  ladder(frac*nu_sig)={fracs}", flush=True)
    print("[build] ...", flush=True)
    net = build_network(p, verbose=False)

    r_sig0 = simulate_field(p, fresh(p, net, 1), 0.0, do_kick=False)
    r_kick = simulate_field(p, fresh(p, net, 1), 0.0, do_kick=True)
    floor0 = float(r_sig0["ext_coh"].max())
    peak = float(r_kick["ext_coh"].max())
    print(f"[controls] sigma=0 floor(max_coh)={floor0:.4f}  kick peak(max_coh)={peak:.4f}",
          flush=True)
    try:
        bar = calibrate_detector([r_sig0["ext_coh"]], r_kick["ext_coh"])["event_on_frac"]
    except UndetectableOperatingPoint as e:
        bar = None
        print(f"[controls] UNDETECTABLE (sigma=0 floor not below kick peak): {e}", flush=True)

    def show(tag, r):
        e = r["ext_coh"]
        line = (f"  {tag:16s} max_coh={e.max():.3f} mean={e.mean():.4f} "
                f"frac>0={float((e>0).mean()):.3f} rE_max={r['rate_E_hz'].max():.0f}Hz "
                f"wall={r['wall_s']:.0f}s")
        if bar is not None:
            c = classify_run(e, r["dt_bin_ms"], op={}, window="A", event_on_frac=bar)
            line += (f"  -> {c['label']}/{c['reason']} n_ev={c['n_events']}/"
                     f"{c['n_events_total']} fton={c['frac_time_on']:.2f} "
                     f"allret={c['all_returned']}")
        print(line, flush=True)

    if bar is not None:
        print(f"[controls] bar event_on_frac={bar:.4f}", flush=True)
    show("sigma=0", r_sig0)
    show("sigma=0+KICK", r_kick)
    for f in fracs:
        r = simulate_field(p, fresh(p, net, 1), f * nu_sig, do_kick=False, noise_seed=3)
        show(f"nokick frac={f:.2f}", r)
    print("\n[controls] read: (1) sigma=0+KICK must be discrete_events (wiring ok, event clears bar);"
          " (2) sigma=0 must be extinction_only; (3) does the ladder show a discrete band, only"
          " sustained, or only extinction? does coh saturate (max~1.0 = need bigger L)?", flush=True)


def run_grid(L, density, T, drives, sigma_fracs, seeds, out_path,
             sig_ref_frac=0.01, n_ref_seeds=3):
    """Multi-seed (drive x sigma_frac) grid. Verdict per cell: accepted_cell(>=60% seeds
    discrete, rate in [0.01,1]/s). Saves JSON. Each drive builds ONE network (same
    topology seed=1) and resets rng per simulation seed so runs are reproducible."""
    results = []
    for drive in drives:
        base = dict(g=3.6, L=L, density=density, T=T, seed=1)
        p = Params(nu_ext_ratio=drive, **base)
        nu_theta = compute_nu_theta(p)[0]
        nu_sig = drive * nu_theta
        print(f"\n[grid] drive={drive}  nu_sig={nu_sig*1e3:.0f}Hz  building...", flush=True)
        net = build_network(p, verbose=False)

        # per-drive calibration references (contract sef_hfo_events §10.2):
        # floor = worst-case over sigma=0 AND a sub-threshold-noise sigma_ref run
        # (must be UNIFORMLY sub-threshold across drives or the floor is event-contaminated;
        #  sig_ref_frac small, multi-seed worst-case). peak = sigma=0 deterministic kick.
        r_floor0 = simulate_field(p, fresh(p, net, 1), 0.0, do_kick=False)
        ref_series = [r_floor0["ext_coh"]]
        for rs in range(1, n_ref_seeds + 1):
            r_ref = simulate_field(p, fresh(p, net, rs), sig_ref_frac * nu_sig,
                                   do_kick=False, noise_seed=1000 + rs)
            ref_series.append(r_ref["ext_coh"])
        r_kick  = simulate_field(p, fresh(p, net, 1), 0.0, do_kick=True)
        floor_wc = max(float(np.max(s)) for s in ref_series)
        try:
            cal = calibrate_detector(ref_series, r_kick["ext_coh"])
            bar = cal["event_on_frac"]
        except UndetectableOperatingPoint:
            bar = None
        print(f"[grid] drive={drive} floor(sig0+sig_ref worst-case)={floor_wc:.4f} "
              f"kick_peak={r_kick['ext_coh'].max():.4f} bar={bar}", flush=True)

        for frac in sigma_fracs:
            sigma_n = frac * nu_sig
            cell_labels = []
            cell_rates = []
            for seed in seeds:
                r = simulate_field(p, fresh(p, net, seed), sigma_n, do_kick=False,
                                   noise_seed=seed * 17)
                e = r["ext_coh"]
                if bar is not None:
                    c = classify_run(e, r["dt_bin_ms"], op={}, window="A",
                                     event_on_frac=bar)
                    is_disc = c["label"] == "discrete_events"
                    ev_rate = c["n_events"] / (T * 1e-3) if is_disc else 0.0
                    cell_labels.append(c["label"])
                    cell_rates.append(ev_rate if is_disc else None)
                    print(f"  drive={drive} frac={frac:.3f} seed={seed} "
                          f"-> {c['label']}/{c['reason']} n_ev={c['n_events']} "
                          f"fton={c['frac_time_on']:.2f} rate={ev_rate:.3f}/s", flush=True)
                else:
                    cell_labels.append("undetectable")
                    cell_rates.append(None)

            n_disc = sum(1 for l in cell_labels if l == "discrete_events")
            frac_disc = n_disc / len(seeds)
            disc_rates = [r for r in cell_rates if r is not None and r > 0]
            mean_rate = float(np.mean(disc_rates)) if disc_rates else None
            acc = accepted_cell(frac_disc, mean_rate)
            results.append(dict(drive=drive, sigma_frac=frac, sigma_n=sigma_n,
                                n_seeds=len(seeds), n_discrete=n_disc,
                                frac_discrete=frac_disc, mean_rate=mean_rate,
                                accepted=acc, labels=cell_labels))
            print(f"  CELL drive={drive} frac={frac:.3f}: {n_disc}/{len(seeds)} disc "
                  f"frac={frac_disc:.2f} mean_rate={mean_rate} accepted={acc}", flush=True)

    summary = dict(drives=drives, sigma_fracs=sigma_fracs, seeds=seeds,
                   L=L, density=density, T=T, cells=results,
                   n_accepted=sum(1 for r in results if r["accepted"]),
                   robust_2d=sum(1 for r in results if r["accepted"]) >= 2)
    with open(out_path, "w") as f:
        json.dump(summary, f, indent=2, default=float)
    print(f"\n[grid] DONE  n_accepted={summary['n_accepted']}  "
          f"robust_2d={summary['robust_2d']}  -> {out_path}", flush=True)
    return summary


def run_tausweep(L, density, T, drive, taus, fracs, seeds, out_path):
    """Advisor blocker (2026-06-05): the robust_2d=False verdict rests entirely on the
    rate gate (events too frequent). Event rate may be set by the noise correlation time
    TAU_NOISE, not by an intrinsic network limit. Sweep tau at the fracs that failed ONLY
    on rate; if slower noise drops the rate into [0.01,1]/s the verdict flips."""
    base = dict(g=3.6, L=L, density=density, T=T, seed=1)
    p = Params(nu_ext_ratio=drive, **base)
    nu_theta = compute_nu_theta(p)[0]
    nu_sig = drive * nu_theta
    print(f"[tausweep] drive={drive} nu_sig={nu_sig*1e3:.0f}Hz taus={taus} fracs={fracs} "
          f"seeds={seeds}  building...", flush=True)
    net = build_network(p, verbose=False)
    r_floor = simulate_field(p, fresh(p, net, 1), 0.0, do_kick=False)
    r_kick  = simulate_field(p, fresh(p, net, 1), 0.0, do_kick=True)
    bar = calibrate_detector([r_floor["ext_coh"]], r_kick["ext_coh"])["event_on_frac"]
    print(f"[tausweep] bar={bar:.4f}", flush=True)

    rows = []
    for tau in taus:
        for frac in fracs:
            rates, labels = [], []
            for seed in seeds:
                r = simulate_field(p, fresh(p, net, seed), frac * nu_sig, do_kick=False,
                                   noise_seed=seed * 17, tau_noise=tau)
                c = classify_run(r["ext_coh"], r["dt_bin_ms"], op={}, window="A",
                                 event_on_frac=bar)
                is_disc = c["label"] == "discrete_events"
                ev_rate = c["n_events"] / (T * 1e-3) if is_disc else 0.0
                rates.append(ev_rate); labels.append(c["label"])
                print(f"  tau={tau:>4.0f} frac={frac:.3f} seed={seed} -> {c['label']} "
                      f"n_ev={c['n_events']} rate={ev_rate:.2f}/s fton={c['frac_time_on']:.2f}",
                      flush=True)
            n_disc = sum(1 for l in labels if l == "discrete_events")
            disc_rates = [x for x in rates if x > 0]
            mean_rate = float(np.mean(disc_rates)) if disc_rates else None
            acc = accepted_cell(n_disc / len(seeds), mean_rate)
            rows.append(dict(tau=tau, frac=frac, n_discrete=n_disc, n_seeds=len(seeds),
                             mean_rate=mean_rate, accepted=acc, labels=labels))
            print(f"  ROW tau={tau:.0f} frac={frac:.3f}: {n_disc}/{len(seeds)} disc "
                  f"mean_rate={mean_rate} accepted={acc}", flush=True)
    summary = dict(drive=drive, taus=taus, fracs=fracs, seeds=seeds, L=L, density=density,
                   T=T, rows=rows, n_accepted=sum(1 for r in rows if r["accepted"]))
    with open(out_path, "w") as f:
        json.dump(summary, f, indent=2, default=float)
    print(f"\n[tausweep] DONE n_accepted={summary['n_accepted']} -> {out_path}", flush=True)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--mode", choices=["controls", "grid", "tausweep"], default="controls")
    ap.add_argument("--taus", type=str, default="150,300,600,1000")
    ap.add_argument("--L", type=float, default=3.0)
    ap.add_argument("--density", type=float, default=1800.0)
    ap.add_argument("--T", type=float, default=1500.0)
    ap.add_argument("--drive", type=float, default=0.6)
    # grid-only args
    ap.add_argument("--drives", type=str, default="0.5,0.6,0.65,0.7")
    ap.add_argument("--fracs", type=str, default="0.0,0.02,0.05,0.10,0.20,0.40")
    ap.add_argument("--seeds", type=str, default="1,2,3")
    ap.add_argument("--out", type=str, default=None)
    args = ap.parse_args()
    if args.mode == "controls":
        run_controls(args.L, args.density, args.T, args.drive)
    elif args.mode == "tausweep":
        taus  = [float(x) for x in args.taus.split(",")]
        fracs = [float(x) for x in args.fracs.split(",")]
        seeds = [int(x)   for x in args.seeds.split(",")]
        out = args.out or os.path.join(DATA, "snn_noise_tausweep.json")
        run_tausweep(args.L, args.density, args.T, args.drive, taus, fracs, seeds, out)
    else:
        drives = [float(x) for x in args.drives.split(",")]
        fracs  = [float(x) for x in args.fracs.split(",")]
        seeds  = [int(x)   for x in args.seeds.split(",")]
        out = args.out or os.path.join(DATA, "snn_noise_grid.json")
        run_grid(args.L, args.density, args.T, drives, fracs, seeds, out)


if __name__ == "__main__":
    main()
